### ISSUE TITLE
^1.3.0 Incompatibility

### ISSUE THREAD

**Issue by qkdreyer** [robinvdvleuten/shvl#2]
warning  in ./node_modules/vuex-persistedstate/dist/vuex-persistedstate.es.js
1:395-396 "export 'default' (imported as 'e') was not found in 'shvl'

https://github.com/robinvdvleuten/shvl/commit/dacc1b87fbf802bb7a5aeef8a032bc905c020fc1

**Comment by dmiotti** [comment]
Same here with vuex-persistedstate !

**Comment by qkdreyer** [comment]
https://github.com/robinvdvleuten/vuex-persistedstate/pull/132

**Comment by dmiotti** [comment]
Thank you for the effort I'm using your branch until it's merged :)

**Comment by qkdreyer** [comment]
No problem, was facing the same issue as yours !

**Comment by robinvdvleuten** [comment]
The issue is resolved in vuex-persistedstate v2.5.2
