### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by william807803** [robinvdvleuten/shvl#3]
![pic](https://camo.githubusercontent.com/4e04ce9a1497085ffa2c2d22ef3373a2a5ed0511/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f3835784c44514c6f5a4431726b3037752f67697068792d646f776e73697a65642e676966)
what's this pic mean ? i cant understand .

**Comment by robinvdvleuten** [comment]
The name "shvl" is "shovel" but without vowels. I needed a funny picture of someone "shoveling" so there you go :)

**Comment by robinvdvleuten** [comment]
And this library helps you with "shoveling" through an object. So it's nice that there is one person really shoveling and one person (this library) helps with that.
